/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlloganRouteImport } from './routes/lllogan'
import { Route as LoganRouteImport } from './routes/logan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlloganRoute = LlloganRouteImport.update({
  id: '/lllogan',
  path: '/lllogan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoganRoute = LoganRouteImport.update({
  id: '/logan',
  path: '/logan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lllogan': typeof LlloganRoute
  '/logan': typeof LoganRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lllogan': typeof LlloganRoute
  '/logan': typeof LoganRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lllogan': typeof LlloganRoute
  '/logan': typeof LoganRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lllogan' | '/logan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lllogan' | '/logan'
  id: '__root__' | '/' | '/lllogan' | '/logan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlloganRoute: typeof LlloganRoute
  LoganRoute: typeof LoganRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lllogan': {
      id: '/lllogan'
      path: '/lllogan'
      fullPath: '/lllogan'
      preLoaderRoute: typeof LlloganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logan': {
      id: '/logan'
      path: '/logan'
      fullPath: '/logan'
      preLoaderRoute: typeof LoganRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlloganRoute: LlloganRoute,
  LoganRoute: LoganRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
